version: '3.8'

services:
  # Swagger API Agent Web 服务
  swagger-web:
    build: .
    command: ["web"]
    ports:
      - "5000:5000"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL:-https://api.deepseek.com}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      - OPENAPI_FILE=/app/examples/example_openapi.yaml
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    volumes:
      - ./examples:/app/examples:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mock 服务器
  mock-server:
    build: .
    command: ["mock"]
    ports:
      - "8080:8080"
    environment:
      - OPENAPI_FILE=/app/examples/example_openapi.yaml
      - MOCK_HOST=0.0.0.0
      - MOCK_PORT=8080
    volumes:
      - ./examples:/app/examples:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # CLI 运行器（一次性任务）
  swagger-cli:
    build: .
    command: ["cli", "--help"]
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=${DEEPSEEK_API_URL:-https://api.deepseek.com}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      - OPENAPI_FILE=/app/examples/example_openapi.yaml
    volumes:
      - ./examples:/app/examples:ro
      - ./logs:/app/logs
    profiles:
      - cli
    
volumes:
  logs:
    driver: local

networks:
  default:
    driver: bridge
